title: Миленочка Чернуцкая
description: "Тут лежит чёта про меня: всякое интересное"
theme: just-the-docs

url: https://czernucka.github.io/just-the-docs-template

<!--
 aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-Template
-->
